name: Publish Package to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main

# cancel previous runs if a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine ruff pytest

      - name: Run tests
        run: |
          python -m pytest

      - name: Run linting
        run: |
          ruff check .

      - name: Build package
        run: |
          python -m build

      - name: Check distribution
        run: |
          python -m twine check dist/*

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
          retention-days: 1

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write  # OIDC authentication
    
    environment:
      name: pypi
      url: https://pypi.org/p/mcp-sentry

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1